dbt_first_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: '172.21.0.5'
      user: 'postgres'
      password: '1234'
      port: 5432
      dbname: 'stage' # or database instead of dbname
      schema: 'f1'
      threads: 10

      